name: "基础配置"
description: "所有主题的通用配置"

# 样式配置
styles:
  border_radius: 12
  box_shadow: "0 8px 24px rgba(0, 0, 0, 0.15)"
  header_padding: "50px 40px"
  content_padding: "40px 50px"
  header_h1_weight: "700"
  header_meta_opacity: "0.9"
  header_text_shadow: "0 2px 4px rgba(0, 0, 0, 0.2)"

# 字体大小
font_sizes:
  header_h1: "2.4em"
  header_meta: "1.05em"
  h1: "2.2em"
  h2: "1.8em"
  h3: "1.4em"
  h4: "1.15em"
  h5: "1.05em"
  body: "15px"
  code: "0.9em"

# 间距
spacing:
  h2_margin: "40px 0 20px 0"
  h3_margin: "30px 0 18px 0"
  h4_margin: "22px 0 12px 0"
  p_margin: "12px 0"

# 渐变定义
gradients:
  background: "linear-gradient(135deg, {{primary}} 0%, {{secondary}} 100%)"
  header: "linear-gradient(135deg, {{primary}} 0%, {{secondary}} 100%)"
  table_header: "linear-gradient(90deg, {{primary}} 0%, {{secondary}} 100%)"
  blockquote: "linear-gradient(135deg, {{primary}} 0%, {{secondary}} 100%)"
  table_hover: "{{table_hover}}"

# 特殊样式
special_styles:
  blockquote:
    border_left: "4px solid {{primary}}"
    border_radius: "0 6px 6px 0"
    padding: "12px 18px"
    font_style: "italic"

  table:
    box_shadow: "0 2px 8px rgba(0, 0, 0, 0.06)"
    border_radius: "8px"
    hover_transition: "background 0.25s ease"

  code_inline:
    background: "#e6f7ff"
    padding: "2px 6px"
    border_radius: "3px"
    color: "#096dd9"

  pre:
    padding: "20px"
    border_radius: "8px"
    box_shadow: "0 2px 8px rgba(0, 0, 0, 0.08)"
